<?php

declare(strict_types=1);

namespace CodeContext\Renderer\Markdown;

use CodeContext\Config\Config;
use CodeContext\Model\ClassInfo;
use CodeContext\Model\Context;
use CodeContext\Model\MethodInfo;
use CodeContext\Model\ParameterInfo;

/**
 * Produces a narrative AGENTS.md file aimed at AI coding assistants.
 *
 * The format is intentionally compact: a short preamble, then one section per namespace,
 * listing classes with kind, parents and public method signatures.
 */
final class AgentsMdRenderer
{
    public function __construct(private readonly Config $config)
    {
    }

    public function render(Context $context): string
    {
        $lines = [];
        $lines[] = '# AGENTS.md';
        $lines[] = '';
        $lines[] = sprintf('_Auto-generated by `code-context` on %s._', $context->generatedAt);
        $lines[] = '';
        $lines[] = sprintf('Project root: `%s`', $context->projectRoot);
        $lines[] = '';
        $lines[] = sprintf('Total classes/interfaces/traits/enums analyzed: **%d**.', \count($context->classes));
        $lines[] = '';

        if ([] === $context->classes) {
            $lines[] = '> No PHP classes were found within the configured `paths.include`.';
            $lines[] = '';

            return implode("\n", $lines);
        }

        if ($this->config->markdownGroupByNamespace()) {
            $this->renderByNamespace($context, $lines);
        } else {
            $this->renderFlat($context, $lines);
        }

        return implode("\n", $lines);
    }

    /**
     * @param list<string> $lines
     */
    private function renderByNamespace(Context $context, array &$lines): void
    {
        $grouped = $context->classesByNamespace();
        foreach ($grouped as $namespace => $classes) {
            $title = '' === $namespace ? '_(global namespace)_' : $namespace;
            $lines[] = '## ' . $title;
            $lines[] = '';
            foreach ($classes as $class) {
                $this->renderClass($class, $lines);
            }
        }
    }

    /**
     * @param list<string> $lines
     */
    private function renderFlat(Context $context, array &$lines): void
    {
        $sorted = $context->classes;
        usort($sorted, static fn (ClassInfo $a, ClassInfo $b): int => $a->fqcn <=> $b->fqcn);
        foreach ($sorted as $class) {
            $this->renderClass($class, $lines);
        }
    }

    /**
     * @param list<string> $lines
     */
    private function renderClass(ClassInfo $class, array &$lines): void
    {
        $modifiers = [];
        if ($class->isAbstract) {
            $modifiers[] = 'abstract';
        }
        if ($class->isFinal && 'enum' !== $class->kind) {
            $modifiers[] = 'final';
        }
        if ($class->isReadonly) {
            $modifiers[] = 'readonly';
        }
        $modPrefix = [] === $modifiers ? '' : implode(' ', $modifiers) . ' ';

        $heading = sprintf('### `%s%s %s`', $modPrefix, $class->kind, $class->shortName);
        $lines[] = $heading;
        $lines[] = '';
        $lines[] = sprintf('- **FQCN**: `%s`', $class->fqcn);
        $lines[] = sprintf('- **File**: `%s`', $class->file);
        if (null !== $class->extends && '' !== $class->extends) {
            $lines[] = sprintf('- **Extends**: `%s`', $class->extends);
        }
        if ([] !== $class->implements) {
            $lines[] = sprintf('- **Implements**: %s', implode(', ', array_map(static fn (string $i): string => '`' . $i . '`', $class->implements)));
        }
        if ([] !== $class->traits) {
            $lines[] = sprintf('- **Uses**: %s', implode(', ', array_map(static fn (string $t): string => '`' . $t . '`', $class->traits)));
        }
        if ([] !== $class->attributes) {
            $lines[] = sprintf('- **Attributes**: %s', implode(', ', array_map(static fn (string $a): string => '`#[' . $a . ']`', $class->attributes)));
        }
        if (null !== $class->summary && '' !== $class->summary) {
            $lines[] = '';
            $lines[] = '> ' . str_replace("\n", "\n> ", $class->summary);
        }
        $lines[] = '';

        $publicMethods = array_values(array_filter(
            $class->methods,
            static fn (MethodInfo $m): bool => 'public' === $m->visibility,
        ));

        if ([] !== $publicMethods) {
            $lines[] = '**Public methods:**';
            $lines[] = '';
            foreach ($publicMethods as $method) {
                $lines[] = '- ' . $this->formatMethodSignature($method);
                if (null !== $method->summary && '' !== $method->summary) {
                    $lines[] = '  - ' . $method->summary;
                }
            }
            $lines[] = '';
        }
    }

    private function formatMethodSignature(MethodInfo $method): string
    {
        $params = array_map(
            fn (ParameterInfo $p): string => $this->formatParameter($p),
            $method->parameters,
        );
        $signature = sprintf('`%s(%s)', $method->name, implode(', ', $params));
        if (null !== $method->returnType) {
            $signature .= ': ' . $method->returnType;
        }
        $signature .= '`';

        $modifiers = [];
        if ($method->isStatic) {
            $modifiers[] = 'static';
        }
        if ($method->isAbstract) {
            $modifiers[] = 'abstract';
        }
        if ($method->isFinal) {
            $modifiers[] = 'final';
        }

        return [] === $modifiers ? $signature : '_' . implode(' ', $modifiers) . '_ ' . $signature;
    }

    private function formatParameter(ParameterInfo $param): string
    {
        $rendered = '';
        if (null !== $param->type) {
            $rendered .= $param->type . ' ';
        }
        if ($param->byReference) {
            $rendered .= '&';
        }
        if ($param->variadic) {
            $rendered .= '...';
        }
        $rendered .= '$' . $param->name;
        if ($param->hasDefault && null !== $param->default) {
            $rendered .= ' = ' . $param->default;
        }

        return $rendered;
    }
}
